-- Migration 026: Author Profiles
-- Supports Feature 6.5 (Article-Grounded Claims).
--
-- Dedicated table for author background information. The existing
-- `papers.authors` JSONB only stores name + openalex_id + orcid + institution,
-- duplicated across every paper the author wrote. Author bio, country, and
-- field belong once-per-author, not per-paper, so they live here and are
-- joined in at query time.
--
-- The join key is openalex_id (preferred) or orcid, falling back to
-- normalized_name for authors with neither. `papers.authors[].author_profile_id`
-- is the canonical pointer once an author has been enriched.

CREATE TABLE IF NOT EXISTS author_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Identity
  openalex_id TEXT UNIQUE,           -- e.g., 'A1969205032' (preferred key)
  orcid TEXT UNIQUE,                 -- e.g., '0000-0002-1825-0097'
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,     -- lowercased, stripped, for fallback matching

  -- Affiliation / location
  primary_institution TEXT,          -- most recent / most frequent institution
  primary_institution_ror_id TEXT,   -- ROR ID for the primary institution
  country TEXT,                      -- ISO 3166-1 alpha-2 (e.g., 'US', 'IL', 'DE')
  institution_history JSONB DEFAULT '[]'::jsonb,
  -- [{institution, ror_id, country, years: [start, end]}]

  -- Scholarly profile
  primary_field TEXT,                -- e.g., 'anthropology', 'economics'
  concepts JSONB DEFAULT '[]'::jsonb,
  -- Top OpenAlex concepts for this author: [{id, name, level, score}]
  works_count INT DEFAULT 0,
  cited_by_count INT DEFAULT 0,
  h_index INT,

  -- Background blurb — short, learner-friendly summary
  -- Generated by Claude from OpenAlex author record + top works
  bio TEXT,
  bio_model TEXT,                    -- which model produced the bio
  bio_generated_at TIMESTAMPTZ,

  -- Enrichment tracking
  enriched_at TIMESTAMPTZ,           -- when this profile was populated / last refreshed
  enrichment_source TEXT,            -- 'openalex' | 'manual' | other

  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Updated_at trigger (function already exists from migration 006)
CREATE TRIGGER author_profiles_updated_at
  BEFORE UPDATE ON author_profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Lookup indexes
CREATE INDEX IF NOT EXISTS idx_author_profiles_openalex ON author_profiles(openalex_id);
CREATE INDEX IF NOT EXISTS idx_author_profiles_orcid ON author_profiles(orcid);
CREATE INDEX IF NOT EXISTS idx_author_profiles_normalized_name ON author_profiles(normalized_name);
CREATE INDEX IF NOT EXISTS idx_author_profiles_country ON author_profiles(country);
CREATE INDEX IF NOT EXISTS idx_author_profiles_primary_field ON author_profiles(primary_field);

-- Pending-enrichment partial index (for batch backfill jobs)
CREATE INDEX IF NOT EXISTS idx_author_profiles_pending_enrichment
  ON author_profiles(id)
  WHERE enriched_at IS NULL;

-- Pending-bio partial index (bio generation is separate / more expensive)
CREATE INDEX IF NOT EXISTS idx_author_profiles_pending_bio
  ON author_profiles(id)
  WHERE bio IS NULL;
