"""Privacy-aware paper view.

For papers uploaded by users:
  - The owner sees title, abstract, full_text, analysis — everything.
  - Other users see ONLY the derived analysis (concepts, claims,
    relationships) plus a short autogenerated summary. The verbatim
    abstract and full_text are withheld.

For papers seeded from public sources (canonical, OpenAlex, etc.):
  - Everyone sees everything (no change in behavior).

This implements the "transform, don't share" model agreed on:
Korczak learns from anything users upload, but never redistributes
copyrighted text to other users.
"""

import logging
from typing import Optional

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

from backend.integrations import supabase_client as db

logger = logging.getLogger(__name__)
router = APIRouter()


class PaperView(BaseModel):
    id: str
    title: Optional[str]
    publication_year: Optional[int]
    authors: Optional[list]
    source_journal: Optional[str]
    cited_by_count: int = 0
    canonical: bool = False
    canonical_field: Optional[str] = None
    is_owner: bool = False
    text_private: bool = False
    abstract: Optional[str] = None  # populated only for owner or public papers
    full_text: Optional[str] = None  # owner-only when text_private
    analysis: Optional[dict] = None  # always public — transformative
    summary: Optional[str] = None  # short safe summary if text_private
    concepts: list = []
    claims: list = []


def _safe_summary_from_analysis(analysis: dict | None) -> Optional[str]:
    if not analysis:
        return None
    pt = analysis.get("paper_type") or {}
    summary = pt.get("summary")
    if summary:
        return summary
    # Fallback: assemble from concepts
    concepts = analysis.get("concepts") or []
    if concepts:
        names = ", ".join(c.get("name", "") for c in concepts[:5])
        return f"Analysis identifies key concepts: {names}."
    return None


@router.get("/papers/{paper_id}/view", response_model=PaperView)
async def view_paper(
    paper_id: str,
    requester_id: Optional[str] = Query(default=None,
        description="The user requesting the paper. Owners get full access; others see analysis only when text_private=true."),
):
    """Return a paper view that respects upload privacy.

    Anyone can call this endpoint; what comes back depends on whether
    the requester owns the paper and whether text_private is set.
    """
    try:
        client = db.get_client()
        rows = (
            client.table("papers")
            .select("*")
            .eq("id", paper_id)
            .limit(1)
            .execute()
        ).data
        if not rows:
            raise HTTPException(404, detail="Paper not found")
        p = rows[0]

        is_owner = bool(p.get("uploaded_by") and requester_id and str(p["uploaded_by"]) == str(requester_id))
        text_private = bool(p.get("text_private"))

        # Authors come back as JSON string in some rows, list in others; normalize.
        authors_raw = p.get("authors")
        if isinstance(authors_raw, str):
            try:
                import json as _json
                authors = _json.loads(authors_raw)
            except Exception:
                authors = []
        else:
            authors = authors_raw or []

        analysis = p.get("analysis")
        if isinstance(analysis, str):
            try:
                import json as _json
                analysis = _json.loads(analysis)
            except Exception:
                analysis = None

        # Concepts via paper_concepts join
        concepts: list = []
        claims: list = []
        try:
            cps = (
                client.table("paper_concepts")
                .select("concept_id,novelty_in_paper,well_established,concepts(name,type,definition)")
                .eq("paper_id", paper_id)
                .execute()
            ).data
            concepts = [{
                "id": c["concept_id"],
                "name": (c.get("concepts") or {}).get("name"),
                "type": (c.get("concepts") or {}).get("type"),
                "definition": (c.get("concepts") or {}).get("definition"),
                "novelty_in_paper": c.get("novelty_in_paper"),
                "well_established": c.get("well_established"),
            } for c in cps]
        except Exception:
            concepts = []
        try:
            claim_rows = (
                client.table("claims")
                .select("id,claim_text,evidence_type,strength,testable,claim_category")
                .eq("paper_id", paper_id)
                .execute()
            ).data
            claims = claim_rows or []
        except Exception:
            claims = []

        view = PaperView(
            id=str(p["id"]),
            title=p.get("title"),
            publication_year=p.get("publication_year"),
            authors=authors[:10] if isinstance(authors, list) else [],
            source_journal=p.get("source_journal"),
            cited_by_count=p.get("cited_by_count") or 0,
            canonical=bool(p.get("canonical")),
            canonical_field=p.get("canonical_field"),
            is_owner=is_owner,
            text_private=text_private,
            abstract=p.get("abstract") if (not text_private or is_owner) else None,
            full_text=p.get("full_text") if is_owner else None,
            analysis=analysis,  # always public — transformative
            summary=_safe_summary_from_analysis(analysis) if (text_private and not is_owner) else None,
            concepts=concepts,
            claims=claims,
        )
        return view
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("Privacy view failed")
        raise HTTPException(500, detail=str(e))


@router.post("/papers/{paper_id}/privacy")
async def set_privacy(
    paper_id: str,
    text_private: bool = Query(...),
    requester_id: str = Query(..., description="Must match uploaded_by"),
):
    """Owner-only: toggle text_private on their uploaded paper."""
    try:
        client = db.get_client()
        rows = (
            client.table("papers").select("uploaded_by").eq("id", paper_id).limit(1).execute()
        ).data
        if not rows:
            raise HTTPException(404, detail="Paper not found")
        if not rows[0].get("uploaded_by") or str(rows[0]["uploaded_by"]) != str(requester_id):
            raise HTTPException(403, detail="Only the uploader can change privacy")
        client.table("papers").update({"text_private": text_private}).eq("id", paper_id).execute()
        return {"ok": True, "text_private": text_private}
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("set_privacy failed")
        raise HTTPException(500, detail=str(e))
